### ISSUE TITLE
Add documentation on async operations in steps and hooks

### ISSUE THREAD

**Issue by kaustavdm** [getgauge-contrib/gauge-js#36]

**Comment by philipbeadle** [comment]
This is what I did to get webdriver.io checking the google home page title.

package.json

```
{
  "name": "gauge-test",
  "version": "1.0.0",
  "description": "testing out gauge with webdriver",
  "main": "step_implementation.js",
  "directories": {
    "test": "tests"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "chai": "^3.5.0",
    "chai-as-promised": "^5.2.0",
    "webdriverio": "^4.0.3",
    "webdriverjs-angular": "^0.1.3"
  }
}
```

spec file

```
#This spec is an example on how to use Asynch operqtions with webdriver.io

Check the title
---------------------------
* Check the title of the Google home page is "Google"
```

step file

```
'use strict'

var webdriverio = require('webdriverio');
var options = {
  desiredCapabilities: {
    browserName: 'firefox'
  }
};
var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');

chai.use(chaiAsPromised);
expect = chai.expect;
chai.Should();

var assert = require("assert");

gauge.step("Check the title of the Google home page is <vowels>", function (titleGiven, done) {
  webdriverio
    .remote(options)
    .init()
    .url('http://google.com')
    .getTitle().then(function(title) {
      assert(title, titleGiven);
    })
    .end()
    .call(done);
});

```

Enjoy.

**Comment by kaustavdm** [comment]
@philipbeadle This is superb! Thanks a lot!

**Comment by ivanbportugal** [comment]
Will definitely be giving this a shot today! Might be worth adding this to the README? What do you guys think?

**Comment by kaustavdm** [comment]
@ivanbportugal There's a new release with the latest fixes. :smile: You may want to do:

```
$ gauge --update js
```

**Comment by kaustavdm** [comment]
Also, the docs have been updated with information on [async operations](https://github.com/getgauge-contrib/gauge-js#async-operations).

**Comment by philipbeadle** [comment]
thanx so much, youre doing an amazing job with this plugin.  I'm building a full blown demo of using gauge-js with a meteor site and webdriver.io.  Ill keep you posted.

**Comment by kaustavdm** [comment]
@philipbeadle That's lovely. If the demo you are building can be shared, would you mind uploading it as a repo on Github? That way, we can share it with others.

**Comment by philipbeadle** [comment]
demo will be here very soon

https://github.com/philipbeadle/gauge-js-angular-webdriver-demo

**Comment by kaustavdm** [comment]
:smiley_cat: :+1: :beers:

**Comment by philipbeadle** [comment]
Demo is up, basic demo showing using Gauge, gauge-js, angular and webdriver.io to do UI testing :)

https://github.com/philipbeadle/gauge-js-angular-webdriver-demo

**Comment by kaustavdm** [comment]
@philipbeadle Nice! Do you mind if we add it as an example for `gauge-js` to the README?

**Comment by philipbeadle** [comment]
Please do.  I'm going to add to it over the next few weeks and show how to select elements etc and build up a library set hooks etc.

**Comment by ivanbportugal** [comment]
This is great (I think) but I'm getting a timeout error. @philipbeadle were you able to get it past this?

```
λ npm test

> OxyLiftTests@1.0.0 test C:\Users\portugai\(restOfPath)\workbench\gauge
> gauge specs/

# I should be able to see the Google home page
  ## Check the title     F
        Failed Step: Check the title of the Google home page is "Google"
        Error Message: Error: Timed out
        Stacktrace:
        Error: Timed out
            at null.<anonymous> (C:\Users\portugai\AppData\Roaming\gauge\plugins\js\1.1.0\src\test.js:42:23)
            at Timer.listOnTimeout (timers.js:92:15)


Successfully generated html-report to => C:\Users\portugai\(restOfPath)\workbench\gauge\reports\html-report
Specifications: 1 executed      0 passed        1 failed        0 skipped
Scenarios:      1 executed      0 passed        1 failed        0 skipped

Total time taken: 1.324s
npm ERR! Test failed.  See above for more details.
```

I had to add a `var` in front of expect too:

```
'use strict'

var webdriverio = require('webdriverio');
var options = {
  desiredCapabilities: {
    browserName: 'chrome'
  }
};
var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');

chai.use(chaiAsPromised);
var expect = chai.expect;
chai.Should();

var assert = require("assert");

gauge.step("Check the title of the Google home page is <vowels>", function (titleGiven, done) {
  webdriverio
    .remote(options)
    .init()
    .url('http://google.com')
    .getTitle().then(function(title) {
      assert.equal(title, titleGiven);
    })
    .end()
    .call(done);
});
```

**Comment by ivanbportugal** [comment]
Guys,

How might we get assert errors and gauge messages to show up in the report? The following code (using @philipbeadle example) errors out on the console correctly but doesn't show up on the report. It looks like the closure is not being caught at the gauge js level:

```javascript

'use strict'

var webdriverio = require('webdriverio');
var options = {
  desiredCapabilities: {
    browserName: 'chrome'
  }
};
var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');

chai.use(chaiAsPromised);
var expect = chai.expect;
chai.Should();

var assert = require("assert");

gauge.step("Check the title of the Google home page is <vowels>", function (titleGiven, done) {
  webdriverio
    .remote(options)
    .init()
    .url('http://google.com')
    .getTitle().then(function(title) {
        gauge.message('just a test message'); // Does NOT show up
        expect(title).to.equal('blah'); // Shows on the console, not on the report
        assert.equal(title, 'blah'); // Shows on the console, not on the report
    })
    .end()
    .call(done);
});
```

**Comment by ivanbportugal** [comment]
More info: I get the following error in the console. Still digging...

```
Unable to connect to plugin Html Report 2.0.0. proto: required field "SuiteExecutionResult.SuiteResult.SpecResults.ProtoSpec.Items.Scenario.ScenarioItems.Step.StepExecutionResult.PostHookFailure.StackTrace" not set
```

**Comment by ivanbportugal** [comment]
More info. A workaround might be to use the gauge API to fail a test. How might this be done? `gauge.error(e)` or `gauge.step.fail(e)` or `done(e)` ?

```javascript
gauge.step("Check the title of the Google home page is <vowels>", function (titleGiven, done) {

    webdriverio
        .remote(options)
        .init()
        .once('error', function(e) {
            gauge.message('Here is the error: ' + e);
            // Would be nice if we could say: gauge.error(e) or gauge.fail(e) ?
            // Or, maybe even done(e)
        })
        .url('http://google.com')
        .getTitle().then(function(title) {
            try{
                gauge.message('just a test message'); // Shows up
                expect(title).to.equal('blah'); // Throws AssertionError
                assert.equal(title, 'blah'); // Throws AssertionError if you comment out the above line
            } catch(e) {
                this.emit('error', e);
            }
        })
        .end()
        .call(done);
});
```

If you debug, after calling `done(e)` that param doesn't show up in the `err` variable here:
Snippet from `test.js` in your gaugejs library:
```javascript
var done = function(err) {
  var self = this;
  if(self.finished || self.timedOut) {
    return;
  }
  self.duration = new Date() - self.start;
  self.finished = true;
  clearTimeout(self.timer);

  if(err) {
    self.deferred.reject({
      exception: err,
      duration: self.duration
    });
    return;
  } else{
    self.deferred.resolve({
      duration: self.duration
    });
    return;
  }
};
```

**Comment by ivanbportugal** [comment]
Sorry for the busy-ness of this, I think I found a solution. I have a fix. Let me do a PR so you can check it out.

**Comment by philipbeadle** [comment]
Yes you need to set the timeout property in the js.properties file.

And lastly we need to increase the timeout from 1 second to about 30. Open the tests/env/default/js.properties file and set the timeout to 30 seconds.

Cheers
Phil
