### ISSUE TITLE
AssertionError in hooks crash runner

### ISSUE THREAD

**Issue by kaustavdm** [getgauge-contrib/gauge-js#37]
Sample implementation:

```js
gauge.hooks.beforeScenario(function () {
  assert.equal("a", "b");
});
```

Output:

```
# Specification Heading
  ## Vowel counts in single word
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: 'a' == 'b'
    at Object.gauge.hooks.beforeScenario.tags (step_implementation.js:41:10)
    at runFnAsync (/Users/kaustavd/.gauge/plugins/js/1.0.1/src/test.js:63:11)
    at Test.run (/Users/kaustavd/.gauge/plugins/js/1.0.1/src/test.js:69:16)
    at Object.executeHook [as hook] (/Users/kaustavd/.gauge/plugins/js/1.0.1/src/executor.js:98:68)
    at executeHook (/Users/kaustavd/.gauge/plugins/js/1.0.1/src/message-processor.js:44:26)
    at executeBeforeScenarioHook (/Users/kaustavd/.gauge/plugins/js/1.0.1/src/message-processor.js:65:15)
    at MessageProcessor.getResponseFor (/Users/kaustavd/.gauge/plugins/js/1.0.1/src/message-processor.js:149:40)
    at null.<anonymous> (/Users/kaustavd/.gauge/plugins/js/1.0.1/src/gauge.js:17:22)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)


Unable to connect to plugin Html Report 2.0.1. proto: required field "SuiteExecutionResult.SuiteResult.SpecResults.ProtoSpec.Items.Scenario.PreHookFailure.StackTrace" not set

Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	1 executed	0 passed	1 failed	1 skipped

Total time taken: 11ms
```

**Comment by kaustavdm** [comment]
:+1:
