### ISSUE TITLE
Problem with Gauge 0.8

### ISSUE THREAD

**Issue by wayglem** [getgauge-contrib/gauge-js#52]
Hi,

Since I updated from gauge 0.7 to gauge 0.8 tests are failing.
```
/home/txbj8305/.gauge/plugins/js/1.3.0/node_modules/protobufjs/dist/ProtoBuf.js:2901
                        throw(e);
                        ^

Error: Missing at least one required field for Message .gauge.messages.Message: messageType
    at Error (native)
    at T.ProtoBuf.Reflect.MessagePrototype.decode (/home/txbj8305/.gauge/plugins/js/1.3.0/node_modules/protobufjs/dist/ProtoBuf.js:3218:35)
    at Function.Message.decode (/home/txbj8305/.gauge/plugins/js/1.3.0/node_modules/protobufjs/dist/ProtoBuf.js:2896:37)
    at Object.exports.decode (/home/txbj8305/.gauge/plugins/js/1.3.0/src/message-codec.js:20:29)
    at Socket.messageHandler (/home/txbj8305/.gauge/plugins/js/1.3.0/src/connection.js:17:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

  Error Message: Connection closed [127.0.0.1:50742] cause: EOF
  Stacktrace: 
  

  Error Message: write tcp 127.0.0.1:46843->127.0.0.1:50742: use of closed network connection
  Stacktrace: 
  
Successfully generated html-report to => /home/txbj8305/develop/workspace/HOME/gauge-test/reports/html-report
Specifications:	0 executed	0 passed	0 failed	0 skipped
Scenarios:	0 executed	0 passed	0 failed	0 skipped

Total time taken: 11ms
```

I think it's related to : https://github.com/getgauge/gauge-proto/issues/3 
Any clue ?

**Comment by sriv** [comment]
Gauge 0.8.0 introduced breaking API changes, i.e. it uses Proto3 instead of Proto2 now. As a result all language plugins need to be upgraded too. Javascript runner is yet to be updated. Please, could you wait till the next release of JS runner is out? You can continue using gauge 0.7.0 in the meantime.

**Comment by wayglem** [comment]
Thanks @sriv we'll do that

**Comment by sriv** [comment]
### Dev Notes

protobufjs has undergone major changes and thus introduced breaking API changes in v6.0+. It has better support for promises and async loading.

gauge-js could definitely benefit from an upgrade, but it will require some effort in making the api compatible + testing.
