### ISSUE TITLE
Make failure stack trace cleaner

### ISSUE THREAD

**Issue by zabil** [getgauge-contrib/gauge-js#71]
### Current Behavoir

```
# Specification Heading
  ## Vowel counts in single word
        
        Failed Step: The word "gauge" has "2" vowels.
        Specification: specs/example.spec:19
        Error Message: AssertionError [ERR_ASSERTION]: '2' == 3
        Stacktrace: 
        AssertionError [ERR_ASSERTION]: '2' == 3
            at Object.<anonymous> (tests/step_implementation.js:24:10)
            at Test.runFn (.gauge/plugins/js/2.0.3/src/test.js:51:23)
            at Test.run (.gauge/plugins/js/2.0.3/src/test.js:83:11)
            at Object.executeStep [as step] (.gauge/plugins/js/2.0.3/src/executor.js:46:42)
            at MessageProcessor.executeStep (.gauge/plugins/js/2.0.3/src/message-processor.js:29:26)
            at MessageProcessor.getResponseFor (.gauge/plugins/js/2.0.3/src/message-processor.js:179:40)
            at ExecutionConnection.<anonymous> (.gauge/plugins/js/2.0.3/src/gauge.js:31:17)
            at emitOne (events.js:116:13)
            at ExecutionConnection.emit (events.js:211:7)
            at Socket.messageHandler (.gauge/plugins/js/2.0.3/src/connection.js:17:10)
```

### Expected behavior

```
# Specification Heading
  ## Vowel counts in single word
        
        Failed Step: The word "gauge" has "2" vowels.
        Specification: specs/example.spec:19
        Error Message: AssertionError [ERR_ASSERTION]: '2' == 3
        Stacktrace: 
        AssertionError [ERR_ASSERTION]: '2' == 3
            at Object.<anonymous> (tests/step_implementation.js:24:10)
            [Only project code stacktrace]
```

**Comment by sriv** [comment]
should be available in nightly >= 24/11/2017
