### ISSUE TITLE
Screenshot is not captured even if gauge_screenshot is installed

### ISSUE THREAD

**Issue by sguptatw** [getgauge-contrib/gauge-js#77]
**Expected behavior**
Whenever there is an error. Screenshots should be captured.

**Actual behavior**
Screenshot is not being captured when there is a timeout.

**Steps to replicate**
* Run gauge-lsp-tests on windows
* Getting the error
```
Error: spawnSync gauge_screenshot ENOENT
 F
        Failed Step: ensure code lens has details
        Specification: specs\execution.spec:19
        Error Message: Error: Timed out
        Stacktrace:
        Error: Timed out
            at Timeout.<anonymous> (C:\Users\sswaroop\AppData\Roaming\gauge\plugins\js\2.0.3.nightly-2017-11-23\src\test.js:42:23)
            at ontimeout (timers.js:469:11)
            at tryOnTimeout (timers.js:304:5)
            at Timer.listOnTimeout (timers.js:264:5)
```
> Observe that screenshot is not captured

**Version**
```
Gauge version: 0.9.5.nightly-2017-11-23
Commit Hash: 51cfe8d

Plugins
-------
js (2.0.3.nightly-2017-11-23)
screenshot (0.0.1)
```

**Comment by sriv** [comment]
fix should be in gauge nightly  >= 27/11/2017
